# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `actiontext` gem.
# Please instead update this file by running `bin/tapioca gem actiontext`.


# pkg:gem/actiontext#lib/action_text.rb:8
module ActionText
  extend ::ActiveSupport::Autoload

  class << self
    # pkg:gem/actiontext#lib/action_text/engine.rb:12
    def railtie_helpers_paths; end

    # pkg:gem/actiontext#lib/action_text/engine.rb:12
    def railtie_namespace; end

    # pkg:gem/actiontext#lib/action_text/engine.rb:12
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # pkg:gem/actiontext#lib/action_text/engine.rb:12
    def table_name_prefix; end

    # pkg:gem/actiontext#lib/action_text/engine.rb:12
    def use_relative_model_naming?; end
  end
end

# pkg:gem/actiontext#lib/action_text/attachable.rb:4
module ActionText::Attachable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Attachable::ClassMethods

  # pkg:gem/actiontext#lib/action_text/attachable.rb:66
  def as_json(*_arg0); end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:46
  def attachable_content_type; end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:50
  def attachable_filename; end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:54
  def attachable_filesize; end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:58
  def attachable_metadata; end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:42
  def attachable_sgid; end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:62
  def previewable_attachable?; end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:74
  def to_attachable_partial_path; end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:78
  def to_rich_text_attributes(attributes = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/attachable.rb:70
  def to_trix_content_attachment_partial_path; end

  class << self
    # pkg:gem/actiontext#lib/action_text/attachable.rb:22
    def from_attachable_sgid(sgid, options = T.unsafe(nil)); end

    # pkg:gem/actiontext#lib/action_text/attachable.rb:10
    def from_node(node); end

    private

    # pkg:gem/actiontext#lib/action_text/attachable.rb:29
    def attachable_from_sgid(sgid); end
  end
end

# pkg:gem/actiontext#lib/action_text/attachable.rb:36
module ActionText::Attachable::ClassMethods
  # pkg:gem/actiontext#lib/action_text/attachable.rb:37
  def from_attachable_sgid(sgid); end
end

# pkg:gem/actiontext#lib/action_text/attachable.rb:7
ActionText::Attachable::LOCATOR_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/actiontext#lib/action_text.rb:25
module ActionText::Attachables
  extend ::ActiveSupport::Autoload
end

# pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:5
class ActionText::Attachables::ContentAttachment
  include ::ActiveModel::Validations
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Conversion
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::API
  include ::ActiveModel::Model
  extend ::ActiveModel::Validations::ClassMethods
  extend ::ActiveModel::Naming
  extend ::ActiveModel::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveModel::Translation
  extend ::ActiveModel::Validations::HelperMethods
  extend ::ActiveModel::Conversion::ClassMethods

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def __callbacks; end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def __callbacks?; end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def _run_validate_callbacks(&block); end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def _validate_callbacks; end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def _validators; end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def _validators?; end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:20
  def attachable_plain_text_representation(caption); end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def model_name(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:17
  def name; end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:17
  def name=(_arg0); end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:29
  def to_partial_path; end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:33
  def to_trix_content_attachment_partial_path; end

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def validation_context; end

  private

  # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
  def validation_context=(_arg0); end

  class << self
    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
    def __callbacks; end

    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
    def __callbacks=(value); end

    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
    def __callbacks?; end

    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
    def _validate_callbacks; end

    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
    def _validate_callbacks=(value); end

    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
    def _validators; end

    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
    def _validators=(value); end

    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:6
    def _validators?; end

    # pkg:gem/actiontext#lib/action_text/attachables/content_attachment.rb:8
    def from_node(node); end
  end
end

# pkg:gem/actiontext#lib/action_text/attachables/missing_attachable.rb:5
module ActionText::Attachables::MissingAttachable
  extend ::ActiveModel::Naming

  # pkg:gem/actiontext#lib/action_text/attachables/missing_attachable.rb:6
  def model_name(*_arg0, **_arg1, &_arg2); end

  class << self
    # pkg:gem/actiontext#lib/action_text/attachables/missing_attachable.rb:8
    def to_partial_path; end
  end
end

# pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:5
class ActionText::Attachables::RemoteImage
  extend ::ActiveModel::Naming

  # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:30
  def initialize(attributes = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:37
  def attachable_plain_text_representation(caption); end

  # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:28
  def content_type; end

  # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:28
  def height; end

  # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:6
  def model_name(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:41
  def to_partial_path; end

  # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:28
  def url; end

  # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:28
  def width; end

  class << self
    # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:9
    def from_node(node); end

    private

    # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:20
    def attributes_from_node(node); end

    # pkg:gem/actiontext#lib/action_text/attachables/remote_image.rb:16
    def content_type_is_image?(content_type); end
  end
end

# pkg:gem/actiontext#lib/action_text/attachment.rb:6
class ActionText::Attachment
  include ::ActionText::Attachments::Caching
  include ::ActionText::Attachments::Minification
  include ::ActionText::Attachments::TrixConversion
  extend ::ActionText::Attachments::Minification::ClassMethods
  extend ::ActionText::Attachments::TrixConversion::ClassMethods

  # pkg:gem/actiontext#lib/action_text/attachment.rb:55
  def initialize(node, attachable); end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:50
  def attachable; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:60
  def caption; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:64
  def full_attributes; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:88
  def inspect; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:53
  def method_missing(method, *args, **_arg2, &block); end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:50
  def node; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:9
  def tag_name; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:9
  def tag_name=(val); end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:80
  def to_html; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:52
  def to_param(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:72
  def to_plain_text; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:84
  def to_s; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:68
  def with_full_attributes; end

  private

  # pkg:gem/actiontext#lib/action_text/attachment.rb:97
  def attachable_attributes; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:93
  def node_attributes; end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:53
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/attachment.rb:101
  def sgid_attributes; end

  class << self
    # pkg:gem/actiontext#lib/action_text/attachment.rb:14
    def fragment_by_canonicalizing_attachments(content); end

    # pkg:gem/actiontext#lib/action_text/attachment.rb:26
    def from_attachable(attachable, attributes = T.unsafe(nil)); end

    # pkg:gem/actiontext#lib/action_text/attachment.rb:22
    def from_attachables(attachables); end

    # pkg:gem/actiontext#lib/action_text/attachment.rb:32
    def from_attributes(attributes, attachable = T.unsafe(nil)); end

    # pkg:gem/actiontext#lib/action_text/attachment.rb:18
    def from_node(node, attachable = T.unsafe(nil)); end

    # pkg:gem/actiontext#lib/action_text/attachment.rb:9
    def tag_name; end

    # pkg:gem/actiontext#lib/action_text/attachment.rb:9
    def tag_name=(val); end

    private

    # pkg:gem/actiontext#lib/action_text/attachment.rb:39
    def node_from_attributes(attributes); end

    # pkg:gem/actiontext#lib/action_text/attachment.rb:45
    def process_attributes(attributes); end
  end
end

# pkg:gem/actiontext#lib/action_text/attachment.rb:11
ActionText::Attachment::ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:4
class ActionText::AttachmentGallery
  include ::ActiveModel::Validations
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Conversion
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::API
  include ::ActiveModel::Model
  extend ::ActiveModel::Validations::ClassMethods
  extend ::ActiveModel::Naming
  extend ::ActiveModel::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveModel::Translation
  extend ::ActiveModel::Validations::HelperMethods
  extend ::ActiveModel::Conversion::ClassMethods

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:52
  def initialize(node); end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def __callbacks; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def __callbacks?; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def _run_validate_callbacks(&block); end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def _validate_callbacks; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def _validators; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def _validators?; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:56
  def attachments; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:66
  def inspect; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def model_name(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:50
  def node; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:62
  def size; end

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def validation_context; end

  private

  # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
  def validation_context=(_arg0); end

  class << self
    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
    def __callbacks; end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
    def __callbacks=(value); end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
    def __callbacks?; end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
    def _validate_callbacks; end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
    def _validate_callbacks=(value); end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
    def _validators; end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
    def _validators=(value); end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:5
    def _validators?; end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:41
    def attachment_selector; end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:25
    def find_attachment_gallery_nodes(content); end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:11
    def fragment_by_canonicalizing_attachment_galleries(content); end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:17
    def fragment_by_replacing_attachment_gallery_nodes(content); end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:37
    def from_node(node); end

    # pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:45
    def selector; end
  end
end

# pkg:gem/actiontext#lib/action_text/attachment_gallery.rb:7
ActionText::AttachmentGallery::TAG_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/actiontext#lib/action_text.rb:33
module ActionText::Attachments
  extend ::ActiveSupport::Autoload
end

# pkg:gem/actiontext#lib/action_text/attachments/caching.rb:5
module ActionText::Attachments::Caching
  # pkg:gem/actiontext#lib/action_text/attachments/caching.rb:6
  def cache_key(*args); end

  private

  # pkg:gem/actiontext#lib/action_text/attachments/caching.rb:11
  def cache_digest; end
end

# pkg:gem/actiontext#lib/action_text/attachments/minification.rb:5
module ActionText::Attachments::Minification
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Attachments::Minification::ClassMethods
end

# pkg:gem/actiontext#lib/action_text/attachments/minification.rb:8
module ActionText::Attachments::Minification::ClassMethods
  # pkg:gem/actiontext#lib/action_text/attachments/minification.rb:9
  def fragment_by_minifying_attachments(content); end
end

# pkg:gem/actiontext#lib/action_text/attachments/trix_conversion.rb:7
module ActionText::Attachments::TrixConversion
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Attachments::TrixConversion::ClassMethods

  # pkg:gem/actiontext#lib/action_text/attachments/trix_conversion.rb:22
  def to_trix_attachment(content = T.unsafe(nil)); end

  private

  # pkg:gem/actiontext#lib/action_text/attachments/trix_conversion.rb:29
  def trix_attachment_content; end
end

# pkg:gem/actiontext#lib/action_text/attachments/trix_conversion.rb:10
module ActionText::Attachments::TrixConversion::ClassMethods
  # pkg:gem/actiontext#lib/action_text/attachments/trix_conversion.rb:11
  def fragment_by_converting_trix_attachments(content); end

  # pkg:gem/actiontext#lib/action_text/attachments/trix_conversion.rb:17
  def from_trix_attachment(trix_attachment); end
end

# pkg:gem/actiontext#lib/action_text/attribute.rb:4
module ActionText::Attribute
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Attribute::ClassMethods
end

# pkg:gem/actiontext#lib/action_text/attribute.rb:7
module ActionText::Attribute::ClassMethods
  # pkg:gem/actiontext#lib/action_text/attribute.rb:33
  def has_rich_text(name, encrypted: T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/attribute.rb:61
  def rich_text_association_names; end

  # pkg:gem/actiontext#lib/action_text/attribute.rb:57
  def with_all_rich_text; end
end

# pkg:gem/actiontext#lib/action_text/content.rb:4
class ActionText::Content
  include ::ActionText::Serialization
  include ::ActionText::Rendering
  extend ::ActionText::Serialization::ClassMethods
  extend ::ActionText::Rendering::ClassMethods

  # pkg:gem/actiontext#lib/action_text/content.rb:19
  def initialize(content = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/content.rb:106
  def ==(other); end

  # pkg:gem/actiontext#lib/action_text/content.rb:55
  def append_attachables(attachables); end

  # pkg:gem/actiontext#lib/action_text/content.rb:98
  def as_json(*_arg0); end

  # pkg:gem/actiontext#lib/action_text/content.rb:49
  def attachables; end

  # pkg:gem/actiontext#lib/action_text/content.rb:39
  def attachment_galleries; end

  # pkg:gem/actiontext#lib/action_text/content.rb:33
  def attachments; end

  # pkg:gem/actiontext#lib/action_text/content.rb:9
  def blank?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/content.rb:9
  def empty?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/content.rb:7
  def fragment; end

  # pkg:gem/actiontext#lib/action_text/content.rb:45
  def gallery_attachments; end

  # pkg:gem/actiontext#lib/action_text/content.rb:9
  def html_safe(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/content.rb:102
  def inspect; end

  # pkg:gem/actiontext#lib/action_text/content.rb:29
  def links; end

  # pkg:gem/actiontext#lib/action_text/content.rb:9
  def present?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/content.rb:5
  def render(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/actiontext#lib/action_text/content.rb:67
  def render_attachment_galleries(&block); end

  # pkg:gem/actiontext#lib/action_text/content.rb:60
  def render_attachments(**options, &block); end

  # pkg:gem/actiontext#lib/action_text/content.rb:82
  def to_html; end

  # pkg:gem/actiontext#lib/action_text/content.rb:90
  def to_partial_path; end

  # pkg:gem/actiontext#lib/action_text/content.rb:74
  def to_plain_text; end

  # pkg:gem/actiontext#lib/action_text/content.rb:86
  def to_rendered_html_with_layout; end

  # pkg:gem/actiontext#lib/action_text/content.rb:94
  def to_s; end

  # pkg:gem/actiontext#lib/action_text/content.rb:78
  def to_trix_html; end

  private

  # pkg:gem/actiontext#lib/action_text/content.rb:121
  def attachment_for_node(node, with_full_attributes: T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/content.rb:126
  def attachment_gallery_for_node(node); end

  # pkg:gem/actiontext#lib/action_text/content.rb:117
  def attachment_gallery_nodes; end

  # pkg:gem/actiontext#lib/action_text/content.rb:113
  def attachment_nodes; end

  class << self
    # pkg:gem/actiontext#lib/action_text/content.rb:5
    def default_renderer; end

    # pkg:gem/actiontext#lib/action_text/content.rb:5
    def default_renderer=(val); end

    # pkg:gem/actiontext#lib/action_text/content.rb:12
    def fragment_by_canonicalizing_content(content); end

    # pkg:gem/actiontext#lib/action_text/content.rb:5
    def renderer; end

    # pkg:gem/actiontext#lib/action_text/content.rb:5
    def renderer=(obj); end
  end
end

module ActionText::ContentHelper
  def allowed_attributes; end
  def allowed_attributes=(val); end
  def allowed_tags; end
  def allowed_tags=(val); end
  def render_action_text_attachment(attachment, locals: T.unsafe(nil)); end
  def render_action_text_attachments(content); end
  def render_action_text_content(content); end
  def sanitize_action_text_content(content); end
  def sanitizer; end
  def sanitizer=(val); end
  def scrubber; end
  def scrubber=(val); end

  class << self
    def allowed_attributes; end
    def allowed_attributes=(val); end
    def allowed_tags; end
    def allowed_tags=(val); end
    def sanitizer; end
    def sanitizer=(val); end
    def scrubber; end
    def scrubber=(val); end
  end
end

class ActionText::EncryptedRichText < ::ActionText::RichText
  include ::ActionText::EncryptedRichText::GeneratedAttributeMethods
  include ::ActionText::EncryptedRichText::GeneratedAssociationMethods
end

module ActionText::EncryptedRichText::GeneratedAssociationMethods; end
module ActionText::EncryptedRichText::GeneratedAttributeMethods; end

# pkg:gem/actiontext#lib/action_text/encryption.rb:4
module ActionText::Encryption
  # pkg:gem/actiontext#lib/action_text/encryption.rb:12
  def decrypt; end

  # pkg:gem/actiontext#lib/action_text/encryption.rb:5
  def encrypt; end

  private

  # pkg:gem/actiontext#lib/action_text/encryption.rb:24
  def decrypt_rich_texts; end

  # pkg:gem/actiontext#lib/action_text/encryption.rb:20
  def encrypt_rich_texts; end

  # pkg:gem/actiontext#lib/action_text/encryption.rb:32
  def encryptable_rich_texts; end

  # pkg:gem/actiontext#lib/action_text/encryption.rb:28
  def has_encrypted_rich_texts?; end
end

# pkg:gem/actiontext#lib/action_text/engine.rb:11
class ActionText::Engine < ::Rails::Engine; end

# Fixtures are a way of organizing data that you want to test against; in
# short, sample data.
#
# To learn more about fixtures, read the ActiveRecord::FixtureSet documentation.
#
# === YAML
#
# Like other Active Record-backed models, ActionText::RichText records inherit
# from ActiveRecord::Base instances and can therefore be populated by
# fixtures.
#
# Consider an <tt>Article</tt> class:
#
#   class Article < ApplicationRecord
#     has_rich_text :content
#   end
#
# To declare fixture data for the related <tt>content</tt>, first declare fixture
# data for <tt>Article</tt> instances in <tt>test/fixtures/articles.yml</tt>:
#
#   first:
#     title: An Article
#
# Then declare the ActionText::RichText fixture data in
# <tt>test/fixtures/action_text/rich_texts.yml</tt>, making sure to declare
# each entry's <tt>record:</tt> key as a polymorphic relationship:
#
#   first:
#     record: first (Article)
#     name: content
#     body: <div>Hello, world.</div>
#
# When processed, Active Record will insert database records for each fixture
# entry and will ensure the Action Text relationship is intact.
#
# pkg:gem/actiontext#lib/action_text/fixture_set.rb:38
class ActionText::FixtureSet
  class << self
    # Fixtures support Action Text attachments as part of their <tt>body</tt>
    # HTML.
    #
    # === Examples
    #
    # For example, consider a second <tt>Article</tt> fixture declared in
    # <tt>test/fixtures/articles.yml</tt>:
    #
    #   second:
    #     title: Another Article
    #
    # You can attach a mention of <tt>articles(:first)</tt> to <tt>second</tt>'s
    # <tt>content</tt> by embedding a call to <tt>ActionText::FixtureSet.attachment</tt>
    # in the <tt>body:</tt> value in <tt>test/fixtures/action_text/rich_texts.yml</tt>:
    #
    #   second:
    #     record: second (Article)
    #     name: content
    #     body: <div>Hello, <%= ActionText::FixtureSet.attachment("articles", :first) %></div>
    #
    # pkg:gem/actiontext#lib/action_text/fixture_set.rb:59
    def attachment(fixture_set_name, label, column_type: T.unsafe(nil)); end
  end
end

# pkg:gem/actiontext#lib/action_text/fragment.rb:4
class ActionText::Fragment
  # pkg:gem/actiontext#lib/action_text/fragment.rb:24
  def initialize(source); end

  # pkg:gem/actiontext#lib/action_text/fragment.rb:28
  def find_all(selector); end

  # pkg:gem/actiontext#lib/action_text/fragment.rb:37
  def replace(selector); end

  # pkg:gem/actiontext#lib/action_text/fragment.rb:22
  def source; end

  # pkg:gem/actiontext#lib/action_text/fragment.rb:49
  def to_html; end

  # pkg:gem/actiontext#lib/action_text/fragment.rb:45
  def to_plain_text; end

  # pkg:gem/actiontext#lib/action_text/fragment.rb:53
  def to_s; end

  # pkg:gem/actiontext#lib/action_text/fragment.rb:32
  def update; end

  class << self
    # pkg:gem/actiontext#lib/action_text/fragment.rb:17
    def from_html(html); end

    # pkg:gem/actiontext#lib/action_text/fragment.rb:6
    def wrap(fragment_or_html); end
  end
end

# pkg:gem/actiontext#lib/action_text/html_conversion.rb:4
module ActionText::HtmlConversion
  extend ::ActionText::HtmlConversion

  # pkg:gem/actiontext#lib/action_text/html_conversion.rb:15
  def create_element(tag_name, attributes = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/html_conversion.rb:11
  def fragment_for_html(html); end

  # pkg:gem/actiontext#lib/action_text/html_conversion.rb:7
  def node_to_html(node); end

  private

  # pkg:gem/actiontext#lib/action_text/html_conversion.rb:20
  def document; end
end

# pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:4
module ActionText::PlainTextConversion
  extend ::ActionText::PlainTextConversion

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:7
  def node_to_plain_text(node); end

  private

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:109
  def break_if_nested_list(node, text); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:86
  def bullet_for_li_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:98
  def indentation_for_li_node(node); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:105
  def list_node_depth_for_node(node); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:94
  def list_node_name_for_li_node(node); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:32
  def plain_text_for_block(node, index = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:64
  def plain_text_for_blockquote_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:48
  def plain_text_for_br_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:56
  def plain_text_for_div_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:60
  def plain_text_for_figcaption_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:37
  def plain_text_for_h1_node(node, index = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:74
  def plain_text_for_li_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:40
  def plain_text_for_list(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:12
  def plain_text_for_node(node, index = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:20
  def plain_text_for_node_children(node); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:45
  def plain_text_for_ol_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:37
  def plain_text_for_p_node(node, index = T.unsafe(nil)); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:52
  def plain_text_for_text_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:45
  def plain_text_for_ul_node(node, index); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:28
  def plain_text_method_for_node(node); end

  # pkg:gem/actiontext#lib/action_text/plain_text_conversion.rb:82
  def remove_trailing_newlines(text); end
end

class ActionText::Record < ::ActiveRecord::Base
  include ::ActionText::Record::GeneratedAttributeMethods
  include ::ActionText::Record::GeneratedAssociationMethods
end

module ActionText::Record::GeneratedAssociationMethods; end
module ActionText::Record::GeneratedAttributeMethods; end

# pkg:gem/actiontext#lib/action_text/rendering.rb:7
module ActionText::Rendering
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Rendering::ClassMethods
end

# pkg:gem/actiontext#lib/action_text/rendering.rb:16
module ActionText::Rendering::ClassMethods
  # pkg:gem/actiontext#lib/action_text/rendering.rb:25
  def render(*args, &block); end

  # pkg:gem/actiontext#lib/action_text/rendering.rb:17
  def with_renderer(renderer); end
end

class ActionText::RichText < ::ActionText::Record
  include ::ActionText::RichText::GeneratedAttributeMethods
  include ::ActionText::RichText::GeneratedAssociationMethods

  def autosave_associated_records_for_embeds_attachments(*args); end
  def autosave_associated_records_for_embeds_blobs(*args); end
  def autosave_associated_records_for_record(*args); end
  def blank?(*_arg0, **_arg1, &_arg2); end
  def empty?(*_arg0, **_arg1, &_arg2); end
  def nil?(*_arg0, **_arg1, &_arg2); end
  def present?(*_arg0, **_arg1, &_arg2); end
  def to_plain_text; end
  def to_s(*_arg0, **_arg1, &_arg2); end
  def to_trix_html; end
  def validate_associated_records_for_embeds_attachments(*args); end
  def validate_associated_records_for_embeds_blobs(*args); end
end

module ActionText::RichText::EmbedsAttachmentsAssociationExtension
  def purge; end
  def purge_later; end

  private

  def deprecate(action); end
end

module ActionText::RichText::GeneratedAssociationMethods
  def embeds; end
  def embeds=(attachables); end
  def embeds_attachment_ids; end
  def embeds_attachment_ids=(ids); end
  def embeds_attachments; end
  def embeds_attachments=(value); end
  def embeds_blob_ids; end
  def embeds_blob_ids=(ids); end
  def embeds_blobs; end
  def embeds_blobs=(value); end
  def record; end
  def record=(value); end
  def record_changed?; end
  def record_previously_changed?; end
  def reload_record; end
end

module ActionText::RichText::GeneratedAttributeMethods; end

# pkg:gem/actiontext#lib/action_text/serialization.rb:4
module ActionText::Serialization
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Serialization::ClassMethods

  # pkg:gem/actiontext#lib/action_text/serialization.rb:32
  def _dump(*_arg0); end
end

# pkg:gem/actiontext#lib/action_text/serialization.rb:7
module ActionText::Serialization::ClassMethods
  # pkg:gem/actiontext#lib/action_text/serialization.rb:29
  def _load(content); end

  # pkg:gem/actiontext#lib/action_text/serialization.rb:12
  def dump(content); end

  # pkg:gem/actiontext#lib/action_text/serialization.rb:8
  def load(content); end
end

# pkg:gem/actiontext#lib/action_text/system_test_helper.rb:4
module ActionText::SystemTestHelper
  # Locates a Trix editor and fills it in with the given HTML.
  #
  # The editor can be found by:
  # * its +id+
  # * its +placeholder+
  # * the text from its +label+ element
  # * its +aria-label+
  # * the +name+ of its input
  #
  # Examples:
  #
  #   # <trix-editor id="message_content" ...></trix-editor>
  #   fill_in_rich_text_area "message_content", with: "Hello <em>world!</em>"
  #
  #   # <trix-editor placeholder="Your message here" ...></trix-editor>
  #   fill_in_rich_text_area "Your message here", with: "Hello <em>world!</em>"
  #
  #   # <label for="message_content">Message content</label>
  #   # <trix-editor id="message_content" ...></trix-editor>
  #   fill_in_rich_text_area "Message content", with: "Hello <em>world!</em>"
  #
  #   # <trix-editor aria-label="Message content" ...></trix-editor>
  #   fill_in_rich_text_area "Message content", with: "Hello <em>world!</em>"
  #
  #   # <input id="trix_input_1" name="message[content]" type="hidden">
  #   # <trix-editor input="trix_input_1"></trix-editor>
  #   fill_in_rich_text_area "message[content]", with: "Hello <em>world!</em>"
  #
  # pkg:gem/actiontext#lib/action_text/system_test_helper.rb:32
  def fill_in_rich_text_area(locator = T.unsafe(nil), with:); end
end

module ActionText::TagHelper
  def rich_text_area_tag(name, value = T.unsafe(nil), options = T.unsafe(nil)); end

  class << self
    def id; end
    def id=(val); end
  end
end

# pkg:gem/actiontext#lib/action_text/trix_attachment.rb:4
class ActionText::TrixAttachment
  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:51
  def initialize(node); end

  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:55
  def attributes; end

  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:49
  def node; end

  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:59
  def to_html; end

  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:63
  def to_s; end

  private

  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:68
  def attachment_attributes; end

  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:72
  def composed_attributes; end

  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:80
  def read_json_attribute(name); end

  # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:76
  def read_json_object_attribute(name); end

  class << self
    # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:19
    def from_attributes(attributes); end

    private

    # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:33
    def process_attributes(attributes); end

    # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:37
    def transform_attribute_keys(attributes); end

    # pkg:gem/actiontext#lib/action_text/trix_attachment.rb:41
    def typecast_attribute_values(attributes); end
  end
end

# pkg:gem/actiontext#lib/action_text/trix_attachment.rb:9
ActionText::TrixAttachment::ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/actiontext#lib/action_text/trix_attachment.rb:10
ActionText::TrixAttachment::ATTRIBUTE_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/actiontext#lib/action_text/trix_attachment.rb:8
ActionText::TrixAttachment::COMPOSED_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/actiontext#lib/action_text/trix_attachment.rb:6
ActionText::TrixAttachment::SELECTOR = T.let(T.unsafe(nil), String)

# pkg:gem/actiontext#lib/action_text/trix_attachment.rb:5
ActionText::TrixAttachment::TAG_NAME = T.let(T.unsafe(nil), String)

module ActionView::Helpers
  include ::ActionView::Helpers::SanitizeHelper
  include ::ActionView::Helpers::TextHelper
  include ::ActionView::Helpers::UrlHelper
  include ::ActionView::Helpers::SanitizeHelper
  include ::ActionView::Helpers::TextHelper
  include ::ActionView::Helpers::FormTagHelper
  include ::ActionView::Helpers::FormHelper
  include ::ActionView::Helpers::TranslationHelper

  mixes_in_class_methods ::ActionView::Helpers::UrlHelper::ClassMethods
  mixes_in_class_methods ::ActionView::Helpers::SanitizeHelper::ClassMethods
end

class ActionView::Helpers::FormBuilder
  def rich_text_area(method, options = T.unsafe(nil)); end
end

module ActionView::Helpers::FormHelper
  include ::ActionView::Helpers::UrlHelper
  include ::ActionView::Helpers::SanitizeHelper
  include ::ActionView::Helpers::TextHelper
  include ::ActionView::Helpers::FormTagHelper

  mixes_in_class_methods ::ActionView::Helpers::UrlHelper::ClassMethods
  mixes_in_class_methods ::ActionView::Helpers::SanitizeHelper::ClassMethods

  def rich_text_area(object_name, method, options = T.unsafe(nil)); end
end

module ActionView::Helpers::Tags; end

class ActionView::Helpers::Tags::ActionText < ::ActionView::Helpers::Tags::Base
  include ::ActionView::Helpers::Tags::Placeholderable

  def dom_id(*_arg0, **_arg1, &_arg2); end
  def render; end
end
